services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=golibrary'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
  bucket:
    image: 'quay.io/minio/minio'
    command: server /data --console-address ":9001"
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    ports:
      - '9000:9000'
      - '9001:9001'

